### PR TITLE
UI Suggestions

### LINKED ISSUE #65: UI Suggestions
Taken from ICD Discord:

- [x] Add coffee cup logo
- [x] Showlevel under each statue
- [ ] ~Simple flavor text explaining each feature~ #61 
- [x] Move add task to top of page
- [x] Statue input type as numeric
- [x] Total buffs from statues
- [x] Filter builds by class/subclass
- [x] Fix Broken character edit on mobile

### PR DESCRIPTION
**Pull request by adapap**
Stuff from Discord feedback

Closes #65

### CODE REVIEW

File: src/composables/Cards.ts [hunk 1]
```diff
@@ -453,6 +446,13 @@ export const Cards: Card[] = [
     base: 6,
     source: "King Doot (1/25)",
   },
+  {
```
Comment (Musimaniac) [inline src/composables/Cards.ts:449]: I see where you're coming from, but I still think it should mirror the position in game

**Review by Musimaniac — APPROVED** [review]
